export const movies = [
    { name: "Forrest Gump", emoji: "🏃🍫🍤" },
    { name: "Matrix", emoji: "🕶️💊👽" },
    { name: "Titanic", emoji: "🚢❄️💔" },
    { name: "Jurassic Park", emoji: "🦖🌴🚙" },
    { name: "El Rey León", emoji: "🦁👑🌅" },
    { name: "Star Wars", emoji: "⚔️🚀🌌" },
    { name: "Vengadores", emoji: "🦸‍♂️🦸‍♀️💥" },
    { name: "Harry Potter", emoji: "⚡🧙‍♂️🔮" },
    { name: "Terminator", emoji: "🤖🔫🕶️" },
    { name: "Indiana Jones", emoji: "🤠🔍💎" },
    { name: "Volver al Futuro", emoji: "⏰🚗💥" },
    { name: "El padrino", emoji: "🍕🤵🔫" },
    { name: "Batman", emoji: "🦇♞👨‍🦯" },
    { name: "Pulp Fiction", emoji: "🍔🔫🕶️" },
    { name: "El Señor de los Anillos", emoji: "🧝‍♂️🧙‍♂️🗡️" },
    { name: "El Silenco de los Corderos", emoji: "🔇🐑🍖" },
    { name: "El Club de la pelea", emoji: "👊💼🚽" },
    { name: "El Origen", emoji: "🌀👩‍🚀🎩" },
    { name: "Rocky", emoji: "🏃🏽‍♂️🥊💪" },
    { name: "Barbie", emoji: "👱🏻‍♀️🩰🩷" },
    { name: "Piratas del Caribe", emoji: "🏴‍☠️⛵🏝️" },
    { name: "El Hombre Araña", emoji: "🕷️🏙️🕸️" },
    ];